### ISSUE TITLE
Unable to parse episodes from release name

### ISSUE THREAD

**Issue by theJoeBiz** [Sonarr/Sonarr#1111]
I seem to have found a nuance with the search/parsing. It only happens with one series (that I'm aware of), but I think it could probably be solved with a simple fallback.

Series: Real Time with Bill Maher
Indexer: BroadcastheNet

Every week I have to manually download (THE HORROR) Real Time with Bill Maher and then refresh Sonarr to find it. When I click on the episode in the calendar and do a Manual Search, it comes back with results. Here's an example from last nights episode:

<img width="1006" alt="screen shot 2016-01-30 at 12 04 48 pm" src="https://cloud.githubusercontent.com/assets/189589/12697149/e5fcd68a-c749-11e5-88d0-6bfe3505a12e.png">

As you can see, I get the error "Unable to parse episodes from release name". The search found results, but it won't download because it can't parse the episode from the name of the torrent. For some odd reason on BTN this particular series is always uploaded to the correct SxxExx but the file name itself doesn't include said series/episode numbers. Would it be possible for Sonarr to keep track of the file name regardless of what it is and use the search result from BTN to rename it properly?

**Comment by markus101** [comment]
Change the series type to Daily, Sonarr won't use the date to match the episode unless the series type is Daily.

**Comment by theJoeBiz** [comment]
@markus101 I forgot to mention this in the issue. If I change the series type to Daily it fails to find the episode at all when searching. The problem is that the episode is categorized correctly as Standard on BTN (it's only on once a week), which is why the Standard search finds files, but the actual file name is Daily style so it won't let me download it.

I ran into another similar issue with file names a few months ago with Talking Dead. The search for S05E03 returned results but the file was incorrectly named as S06E03. I guess what I'm asking is if it's possible to fall back to the search query if the file name itself is wonky for whatever reason.

**Comment by markus101** [comment]
>  The problem is that the episode is categorized correctly as Standard on BTN (it's only on once a week), which is why the Standard search finds files

Daily could be renamed to "Date" and Anime renamed to "Absolute" because thats what they really are, Daily is used when the release uses a date instead of SxxEyy formatting. So in this case BTN is in the wrong, they're changing the information on their side.

> I guess what I'm asking is if it's possible to fall back to the search query if the file name itself is wonky for whatever reason.

Assuming the indexer is returning the proper results is not something we'll do, countless times we've seen them return the wrong information. I think the only thing we could do here is search for the episode by standard numbering on BTN eve if the series type is daily, assuming we want to do that. @Taloth thoughts?

**Comment by Taloth** [comment]
I already fixed this days ago, but forgot to push it.

**Comment by TheFlinter** [comment]
I seem to be having the same problem with Gardeners World (I know, I know). 

Sonarr lists the seasons by number, so is currently searching for Gardeners World 49x11, but the only sources I can find list the series as Gardeners World 2016x11.

![image](https://cloud.githubusercontent.com/assets/19794355/15850646/fc0e64dc-2c90-11e6-915d-86e0384d3d34.png)

Is there any way to modify what Sonarr is searching for?

Thanks

**Comment by bhcopeland** [comment]
I am having the same problem as @TheFlinter with Gardeners' World.

**Comment by Taloth** [comment]
Guys, this issue was about BTN exclusively, having the same error message doesn't mean you have the same problem.

That said, the Gardeners release name is rather crappy, '2016 Episode x' should be an airdate or SxEx format, not some convoluted mix. So the parser is never gonna be able to handle it. Sry.
It's the big downside of KAT and public trackers in general, no love for standard naming patterns.

**Comment by k3n85** [comment]
Seems "Real Time With Bill Maher" is still throwing Sonarr for a loop, I did as suggested and changed the series to "daily", then when searching, no episodes come up at all now. Even after deleting the series and re-adding it, still zero results appear now instead of the "Unable to parse episode" and coming up with a lot of results. 
![2017-02-12 18_30_36-real time with bill maher - sonarr](https://cloud.githubusercontent.com/assets/656160/22867632/66732256-f151-11e6-89bd-8bdc0a261ce0.png)

**Comment by Taloth** [comment]
![image](https://cloud.githubusercontent.com/assets/6383890/22894893/eb0dd91a-f21a-11e6-92f6-ec06e0a89725.png)

(PS: BATV's release is using the wrong date. the episode aired the 10th, not the 11th)

**Comment by MoeJoe87** [comment]
Could you please implement a "force download" button even if the release name did not parse?

I have a lot series on asian trackers just named COMPLETE in the release name. No season number or episode numbers....I know they still live in the 80's. ^^

But such a button would be nice and much more better would be an option to parse for complete....i mean the series name is correct and the year also....Complete could indicate its the whole season. They are mostly just one Season

**Comment by erkexzcx** [comment]
Still relevant

**Comment by addellll** [comment]
> Could you please implement a "force download" button even if the release name did not parse?
> 
> I have a lot series on asian trackers just named COMPLETE in the release name. No season number or episode numbers....I know they still live in the 80's. ^^
> 
> But such a button would be nice and much more better would be an option to parse for complete....i mean the series name is correct and the year also....Complete could indicate its the whole season. They are mostly just one Season

I agree that a "force download" button would be great!
