### ISSUE TITLE
Investigate support for Asian series (E### numbering)

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1604]
We somewhat support this format via RSS by treating them as mini series which works if the episode is in season 1, but will fail otherwise. If there are absolute episode numbers for the series then setting the series as anime may also work for multi-season series, but searching will still fail for search since the format is fairly strict (and would fail immediately if no absolute episode numbers is available).

This may need to rely on the advanced parser or may not be feasible if it can't be done reliably.

**Comment by Buster14** [comment]
AFAIK,  the only reliable tracker for asian tvshows for me is avistaz.to, and the format that always works in avistaz search is 
tvshow_title E##
e.g : 
Running Man E435
Infinity Challenge E421
The Legend of the Blue Sea E13

It works that way in jackett too. 
So they seem to disregard season numbering.
If so perhaps the solution is to have an option to not include season number?

**Comment by thezoggy** [comment]
sounds like absolute numbering..

**Comment by Buster14** [comment]
Absolute numbering sets the season number = 1, while not all asian series have single season.. some famous ongoing series have multiple season due to their long running time..
Running Man
http://thetvdb.com/?tab=series&id=284209
Infinity Challenge
http://thetvdb.com/?tab=seasonall&id=248870
Easiest way in my opinion is to have an option to remove season numbering...

**Comment by Taloth** [comment]
So, which episode is Running Man E435?
http://thetvdb.com/?tab=episode&seriesid=284209&seasonid=592288&id=5267598&lid=7
or
http://thetvdb.com/?tab=episode&seriesid=284209&seasonid=592288&id=4944357&lid=7

**Comment by Buster14** [comment]
Running Man uses aired year as season name now.
Running Man E435, isn't released yet, i'm just using it as an example :)
http://thetvdb.com/?tab=seasonall&id=248870
Running Man E1 would be Running Man S2010E01
But in avistaz.tv tracker it would be accepted as simply Running Man E001
Running Man E235 for example, is Running Man S2015E235 in thetvdb,
but in avistaz it's Running Man E235

Infinity Challenge uses normal season naming, 
http://thetvdb.com/?tab=episode&seriesid=284209&seasonid=592288&id=5267598&lid=7
thetvdb = Infinity Challenge S03e435
Avistaz = Infinity Challenge e435

So the consistent pattern is without season numbering, 
Setting the season value as 1 won't work on avistaz.

**Comment by Taloth** [comment]
I was linking to Infinity Challenge as example but accidentally typed Running Man.
My point was that there are 3 episodes on tvdb named E1. Same for E026.

**Comment by Buster14** [comment]
ah my bad, infinity challenge has different absolute and seasonal numbering,
the one avistaz using is the absolute numbering. 
i.e : 
thetvdb = Infinite Challenge S03E443
avistaz =  Infinite Challenge E496
http://thetvdb.com/index.php?id=284209&lid=7&tab=seasonall&order=absolute

**Comment by Taloth** [comment]
So, they're both using absolute numbering. For Running Man it just happens to be the same.

**Comment by Buster14** [comment]
Yes absolute numbering, but the search entry must not use season number, that's the format that works in avistaz.
For running man thetvdb is trying to gap the season - absolute numbering confusion by using aired year as season number, but the episode # remains the same.. 

Avistaz = Running man E328
Thetvdb = Running man S2016E328

http://thetvdb.com/?tab=seasonall&id=248870

**Comment by Buster14** [comment]
Update : running man is captured, but it requires manual import to give it correct season numbering.. a progress at least :)

**Comment by Buster14** [comment]
The problem with these series seems to be (as markus101 said) incomplete absolute number listing..
https://forums.sonarr.tv/t/ongoing-avistaz-asian-series-not-grabbed/15788
Adding them manually is not efficient cause these are ongoing series, they may have years of runtime and hundreds of episodes. 
And thetvdb devs refuse to add them automatically 
https://forums.thetvdb.com/viewtopic.php?f=7&t=39245

So I suggest adding a new series type that relies on "all season" numbering. 
Can sonarr crawl that data from thetvdb?

**Comment by Buster14** [comment]
Please look into this, :)
found another tvshow with incomplete absolute numbering

https://www.thetvdb.com/index.php?id=334993&lid=7&tab=seasonall&order=absolute
To be able to cover new type of  numbering would make sonarr even better  IMO

**Comment by Dnkhatri** [comment]
You guys are making a mistake by lumping all Asian series together. Running man and such shows are more like the daily comedy shows than a tv series. Most Asian dramas are like long movies with only 1 season so are released with episode numbers only. What is actually needed is 2 different categories 1 for dramas and another for variety shows (daily shows). So a category that searches with drama name and episode No should solve the problem for 95% of the shows.

**Comment by Buster14** [comment]
Any chance to fix this? Lots of series are not captured. Dnkhatri's solution could probably work

**Comment by Buster14** [comment]
Bump.. Please consider this, there are some weekly shows that still not grabbed..

**Comment by markus101** [comment]
If you have something meaningful to add, add it, otherwise don't bump the thread. We're aware it exists, it'll be worked on when someone gets around to it.

**Comment by Dnkhatri** [comment]
I convinced kaso to ditch episode and season number while searching for single episode in jackett for avistaz so that solved the problem for single episode searching for normal shows. Now the problem is seasons as most shows have a single season only the whole show is released with complete in the name instead of season number. So would it be possible for sonarr to parse and detect the shows
I am posting some examples of naming formats

```
Just Between Lovers (2017) Complete 1080p HDTV AAC H.264-NEXT
Just Between Lovers (2017) Complete 720p HDTV AAC H.264-NEXT
Just Between Lovers (2017) Complete 450p HDTV AAC H.264-NEXT 
Just Between Lovers (2017) Complete 360p HDTV AAC H.264-NEXT
Black 1080p NF WEB-DL DD+2.0 H264-ARiN
Black (2017) Complete 720p NF WEB-DL DDP2.0 H.264-ARiN
Black (2017) Complete 1080p HDTV AAC H.264-NEXT
Black (2017) Complete 720p HDTV AAC H.264-NEXT
Black (2017) Complete 450p HDTV AAC H.264-NEXT
Black (2017) Complete 360p HDTV AAC H.264-NEXT

```

**Comment by Buster14** [comment]
Does changing the series type to daily fix this? I tested it just now for some of the variety shows and will see if it works after few episodes. I was able to search "ask us anything" after changing to daily though, i don't think i could do it before..

**Comment by Buster14** [comment]
Apparently it doesn't help... Also it seems like it's getting worse now, sonarr used to be able to grab running man shows, now it won't grab the past 5-6 episodes,
I checked thetvdb and it lists complete episodes, so the problem isn't on thetvdb, any idea why?

**Comment by nodiaque** [comment]
Is this a dead case? No comment since 2018

**Comment by InterN0te** [comment]
I have the same problem with 2 French daily series. They have no longer been automatically found for a few weeks and when I download them automatically, only the series is recognized, but not the season or episode.

![image](https://github.com/Sonarr/Sonarr/assets/10882916/88be51aa-7206-4aa1-b825-a3b560be743c)

**Comment by notjhoan** [comment]
Wouldn't adding the letter "E" before the absolute episode number solve this 8 year old issue? It looks like these releases are structured like that. A search for absolute episode "128" wouldn't grab a release from Avistaz unless it searches for episode "E128" instead.

I feel like a toggle to prepend an "E" to the absolute episode number before searching would solve this without having to worry about additional queries and API hits.
